### ISSUE TITLE
Feature Request: Block size should be more flexible and set a runtime

### ISSUE THREAD

**Issue by hansl** [Spxg/fat32#1]
We have a need for much larger block sizes in our case (64kb would be ideal for us). In particular, we might even want to support blocks of variables sizes, without having to implement multiple features at compile time.

The best way to handle this would be to be able to set block size when creating instances of volume. The feature can still be used as a default.

**Comment by Spxg** [comment]
Thank you for your issue. 
      It's difficult for the crate to set BUFFER_SIZE in runtime. As you know, the crate is no_std and no alloc, so the buffer size is const and we can't use vec and other data structures.  
      My idea is that we can enumerate all the size because fat32 can support max size is u16(2 bytes) like 512, 1024, 2048, 4096, 8192 etc.

**Comment by Spxg** [comment]
> We have a need for much larger block sizes in our case (64kb would be ideal for us). In particular, we might even want to support blocks of variables sizes, without having to implement multiple features at compile time.
> 
> The best way to handle this would be to be able to set block size when creating instances of volume. The feature can still be used as a default.

Thank you for your issue. 

It's difficult for the crate to set BUFFER_SIZE in runtime. As you know, the crate is no_std and no alloc, so the buffer size is const and we can't use vec and other data structures.  

My idea is that we can enumerate all the size because fat32 can support max size is u16(2 bytes) like 512, 1024, 2048, 4096, 8192 etc.

**Comment by hansl** [comment]
That would be enough for us for now, thanks, at least having the 64kb feature.

**Comment by Spxg** [comment]
> That would be enough for us for now, thanks, at least having the 64kb feature.


I've updated it, can you test it?  If passed, I will push it to crate. By the way, I haven't updated the code for a long time, and I plan to rewrite it if necessary
